Add documentation for mock interview - interviewee
Proyecto-Nutria/otter-guides pull request #6
Opened 2021-08-24 02:58 UTC by abiisnn

# What does this PR do?
It adds documentation for scheduling a mock interview (for the interviewee).  There are five sections:

:pencil2: Log in
:pencil2:
:pencil2:
:pencil2:
# Evidence

![Evidencia](https://user-images.githubusercontent.com/33185677/130548559-859ab991-4524-4757-a41d-94f58113bb2e.PNG)

2021-08-24 03:20 UTC, searleser97 approved these changes
Fantastique !

2021-08-24 03:22 UTC, searleser97 commented on i18n/es/docusaurus-plugin-content-docs/current/yaos/interviewee/mock-interview.mdx
> +Para empezar, deberás actulizar tu **NutriProfile** (aka tu información básica). Elige tu escuela y sube tu resume **en formato pdf**.
actualizar

2021-08-24 03:24 UTC, searleser97 commented on i18n/es/docusaurus-plugin-content-docs/current/yaos/interviewee/mock-interview.mdx
> +5. **Company applying to:** Elige la compañia con para la que estás aplicando.
"con para" ? no seria solo "para la que..."

2021-08-24 03:36 UTC, akotadi reviewed
A few comments, thanks for the guide. :)

2021-08-24 03:36 UTC, akotadi commented on i18n/es/docusaurus-plugin-content-docs/current/yaos/interviewee/mock-interview.mdx
> +Para iniciar sesión, necesitas una correo de GMAIL (usuario@gmail.com), ya que Proyecto Nutria solo soporta inicio de sesión con Google. Para Iniciar sesión, da click en el boton **LOGIN**.
nit: botón

2021-08-24 03:36 UTC, akotadi commented on i18n/es/docusaurus-plugin-content-docs/current/yaos/interviewee/mock-interview.mdx
> +¡Listo! 🎉 Ahora podrás ver la página para actulizar tu NutriPerfil.
nit: actualizar

2021-08-24 03:36 UTC, akotadi commented on i18n/es/docusaurus-plugin-content-docs/current/yaos/interviewee/mock-interview.mdx
> +¡Listo! ahora puedes *Agendar Mock interviews*, *Ver tus proximas entrevistas* y *Ver el historial de tus entrevistas*.
nit: próximas

2021-08-24 03:36 UTC, akotadi commented on i18n/es/docusaurus-plugin-content-docs/current/yaos/interviewee/mock-interview.mdx
> +3. **Number of Interviews:** ¿Cuántas entrevistas te gustaría hacer en el rango de tiempo que estás registrando? (Tienes derecho de hasta 3, considera que es basado en disponibilidad de entrevistador
basado en *la* disponibilidad

2021-08-24 03:36 UTC, akotadi commented on i18n/es/docusaurus-plugin-content-docs/current/yaos/interviewee/mock-interview.mdx
> +Para agregar tus horarios disponibles para prácticar Mock interviews, da click en el botón **Add availability range**. ***Puedes agregar más de un rango de horario.*
nit: practicar

2021-08-24 03:36 UTC, akotadi commented on i18n/es/docusaurus-plugin-content-docs/current/yaos/interviewee/mock-interview.mdx
> +Cuando tu información acerca del tipo de entrevista y tus horarios esten completos, da click en el botón **SCHEDULE**. ¡Listo! Ahora solo queda esperar a que un entrevistador te agende una mock inter
nit: estén

2021-08-24 03:36 UTC, akotadi commented on i18n/es/docusaurus-plugin-content-docs/current/yaos/interviewee/mock-interview.mdx
> +Cuando un entrevistador te agende una mock entrevista, recibirás un correo como el siguiente:
*mock interview* o *entrevista de práctica*, creo que `mock entrevista` ya suena a mucho spanglish. xD

2021-08-24 03:36 UTC, akotadi commented on i18n/es/docusaurus-plugin-content-docs/current/yaos/interviewee/mock-interview.mdx
> +Para conocer los detalles de tu entrevista, entra al sistema y desde el menu principal selecciona **Incoming mock interviews**
nit: menú

2021-08-24 03:36 UTC, akotadi commented on i18n/es/docusaurus-plugin-content-docs/current/yaos/interviewee/mock-interview.mdx
> +Entra al Discord de Proyecto Nutria, en el día y hora indicados, en el Room que se te indico. (Puedes encontrar los Rooms en la parte izquiera del discord).
nit: indicó
nit: izquierda

2021-08-24 14:21 UTC, searleser97 approved these changes
LGTM

2021-08-24 15:02 UTC, akotadi requested changes
A few details for cleaning purposes, follow this guide to check the translations for buttons and navbar of Docosaurus:
https://github.com/Proyecto-Nutria/otter-guides#json-translations

Also, I tried to run the project in Linux and throw me this kind of errors:
![image](https://user-images.githubusercontent.com/26100917/130639915-d4117416-ba27-4b38-b057-5c72d5f9c1f7.png)
And is because the images are with caps at the end (i.e. `.PNG`), so we need to change that.

Finally, erase the files that I included for example purposes:
https://github.com/Proyecto-Nutria/otter-guides/blob/abi/mock-interview-docs/docs/yaos/interviewee/about.mdx
https://github.com/Proyecto-Nutria/otter-guides/blob/abi/mock-interview-docs/i18n/es/docusaurus-plugin-content-docs/current/yaos/interviewee/about.mdx

As well as their reference:
https://github.com/Proyecto-Nutria/otter-guides/blob/abi/mock-interview-docs/sidebars.js#L26

After erasing you should also run the translations commands to see that everything is fine, probably will say that some things need to be erased, lemme know if you have any other problem.

2021-08-25 03:12 UTC, abiisnn commented on i18n/es/docusaurus-plugin-content-docs/current/yaos/interviewee/login.mdx
> +title: Iniciar sesion
Done, let me know if I'm missing something.

2021-08-25 03:38 UTC, akotadi approved these changes
Awesome! Thanks for it.

2021-08-25 03:45 UTC, merged